language: cpp
sudo: required

os:
   - linux

compiler: 
   - clang

apt:
   sources:
      - llvm-toolchain-trusty
      - ubuntu-toolchain-r-test
   packages:
      - clang-9
      - cmake
      - python3

script:
   - mkdir build
   - cd build
   - cmake ../ -DCMAKE_EXPORT_COMPILE_COMMANDS=On -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON
   - make
   
