language: cpp
sudo: required

os:
   - linux

compiler: 
   - clang

before_install:
   - sudo apt-get update
   - sudo apt-get -y install python3
   - sudo apt-get -y install clang
   - sudo apt-get -y install cmake

script:
   - alias python=python3
   - mkdir build
   - cd build
   - cmake ../ -DCMAKE_EXPORT_COMPILE_COMMANDS=On -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON
   - make
   
